#ifndef SMART_COMMANDS
#define SMART_COMMANDS

#define SAMPLERATE             "RSAMP:%d"
#define MODEPOSITION           "MP:%d"
#define SETRELATIVETARGET      "PRT:%d=%ld"
#define SETTARGET              "PT:%d=%ld"
#define STOREVELO              "vv:%d=%f"
#define HOME                   "RUN:%d"
#define MODEVELOCITY           "MV:%d"
#define STOPAXIS               "S:%d"
#define OFFSET                 "O:%d=%ld"
#define REPORTPOSTARGET        "RPT:%d"
#define TURNOFF                "OFF:%d"
#define SETPROPORTIONAL        "KP:%d=%d"
#define SETINTEGRAL            "KI:%d=%d"
#define SETDERIVATIVE          "KD:%d=%d"
#define SWLIMITENABLE          "SLE:%d"
#define SWLIMITMODE            "SLM(0):%d"
#define SWLIMITPLUS            "SLP:%d=%ld"
#define SWLIMITMINUS           "SLN:%d=%ld"
#define SETVELO                "VT:%d=%ld"
#define SETACC                 "ADT:%d=%ld"
#define GO                     "G:%d"
#define BRAKEENGAGE            "BRKENG:%d"
#define BRAKERELEASE           "BRKRLS:%d"
#define CLEARFAULTS            "ZS:%d"
#define REPORTVELOCITY         "RVA:%d"
#define REPORTPOSITION         "RPA:%d"
#define REPORTCMDEDPOS         "RPC:%d"
#define REPORTTEMP             "RTEMP"
#define REPORTCURRENT          "RUIA:%d"
#define REPORTEXTENC           "RCTR(1):%d"
#define REPORTSTATUS0          "RW(0):%d"
#define REPORTSTATUS2          "RW(2):%d"
#define REPORTSTATUS3          "RW(3):%d"
#define REPORTSTATUS12         "RW(12):%d"
#define REPORTTRAJECTORY       "RW(7)"
#define STOP                   "S:0"
#define GOSYNC                 "GOSUB(%d)"
#define CLEARSYNCFLAG          "UR(0):0"

#endif
